#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <PIPEWIRE_NODE_ID> <CROP_WIDTH> <CROP_HEIGHT>" >&2
  exit 1
fi

NODE="$1"
CROP_W="$2"
CROP_H="$3"
TMP="$4"
OUT="~/Documents/obj-recording.mp4"

# Audio source should be properly given to the script later. This had audio just as a test
gst-launch-1.0 -e \
  pipewiresrc path="$NODE" do-timestamp=true ! queue ! \
    videoconvert ! videorate ! \
    video/x-raw,format=I420,framerate=60/1 ! \
    x264enc bitrate=10000 speed-preset=superfast tune=zerolatency ! queue ! mux. \
  pulsesrc device="alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" ! queue ! \
    audioconvert ! audioresample ! flacenc ! queue ! mux. \
  matroskamux name=mux ! filesink location="$TMP"

ffmpeg -y -i "$TMP" \
  -filter:v "crop=${CROP_W}:${CROP_H}:0:0" \
  -c:v libx264 -preset superfast -crf 23 \
  -c:a copy \
  "$OUT"

rm -f "$TMP"

