#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 5 ]; then
  echo "Usage: $0 <PIPEWIRE_VIDEO_NODE_ID> <CROP_WIDTH> <CROP_HEIGHT> <TMP_FILE> <FPS>" >&2
  exit 1
fi

VIDEO_NODE="$1"
CROP_W="$2"
CROP_H="$3"
TMP="$4"
FPS="$5/1"

DEFAULT_SINK=$(pactl get-default-sink)
MONITOR_SRC="${DEFAULT_SINK}.monitor"

gst-launch-1.0 -e \
  pipewiresrc path="$VIDEO_NODE" do-timestamp=true ! queue ! \
    videoconvert ! \
    video/x-raw,format=I420! \
    x264enc pass=qual quantizer=18 speed-preset=medium ! queue ! mux. \
  pulsesrc device="$MONITOR_SRC" do-timestamp=true ! queue ! \
    audio/x-raw,format=S16LE,channels=2,rate=48000 ! \
    audioconvert ! audioresample ! opusenc ! queue ! mux. \
  matroskamux name=mux ! filesink location="$TMP"


timestamp=$(date '+%F_%H_%M')
OUT="$HOME/Documents/obj-recording_$timestamp.mp4"
ffmpeg -y -i "$TMP" \
  -filter:v "crop=${CROP_W}:${CROP_H}:0:0,fps=$FPS" \
  -c:v libx264 -preset superfast -crf 23 \
  -c:a copy \
  "$OUT"

rm -f "$TMP"
echo "ALL DONE #!#!# saved to $OUT"
