#!/usr/bin/env bash
set -euo pipefail


FPS="$1"
WINDOW_ID="$2"
OUT_DIR="$HOME/Documents/Recordings"

echo "Selected window ID: $WINDOW_ID" > log.txt

if [ "$#" -ne 2 ]; then
    notify-send "problem with the program's arguments encountered. Exiting"
    exit 1
fi


for cmd in gst-launch-1.0 xdotool pactl; do
  if ! command -v "$cmd" &> /dev/null; then
    notify-send "Error: Required command '$cmd' is not installed."
    notify-send "Please install it to continue."
    exit 1
  fi
done

notify-send "Please select the window you want to record by clicking on it."

mkdir -p "$OUT_DIR"
timestamp=$(date '+%F_%H-%M-%S')
OUT_FILE="$OUT_DIR/objection_recording_${timestamp}.mp4"

MONITOR_SRC=$(pactl get-default-sink).monitor


gst-launch-1.0 -e \
    ximagesrc xid="$WINDOW_ID" use-damage=0 ! "video/x-raw,framerate=${FPS}/1" ! \
    videoconvert ! \
    x264enc speed-preset=ultrafast tune=zerolatency ! \
    mp4mux name=mux ! \
    filesink location="$OUT_FILE" \
    pulsesrc device="$MONITOR_SRC" ! \
    audioconvert ! \
    avenc_aac ! \
    mux.

echo "ALL DONE #!#!# SAVED TO $OUT_FILE"
